# YOUR NAME OR TITLE OF YOUR SITE
name: Marcelo Andrade

# YOUR BRAND/PERSONAL TAGLINE
tagline: Senior Site Reliability Engineer (SRE), Kubernetes specialist & Multi cloud Architect. Colecionador de perfumes, capitais do mundo e certificações profissionais. 

# YOUR/BRAND IMAGE URL
Image_URL: https://avatars.githubusercontent.com/u/70050534?v=4 

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://devsres.com/links/images/cover.png

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: marcelo_devsres
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # TWITCH
  - Name: Twitch
    URL: 'https://twitch.tv'
    Username: marcelo_devsres 
    Icon-Class: fab fa-twitch
    Color: '#9147fe'
    Text_Color: '#ffffff'

    # YOUTUBE
  - Name: YouTube
    URL: https://www.youtube.com/channel
    Username: UCgbbwB1Wxndh8urBPpyx9XA 
    Color: '#ff0000'
    Icon-Class: fab fa-youtube

  # DEV.TO
  - Name: Dev.to
    URL: 'https://dev.to'
    Username: marcelo_devsres 
    Icon-Class: fab fa-dev
    Color: '#ffffff'
    Text_Color: '#000000'

    # LINKEDIN
  - Name: LinkedIn
    URL: https://www.linkedin.com/in
    Username: marcelo-devsres 
    Color: '#2867B2'
    Icon-Class: fab fa-linkedin-in

    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: marcelo-devsres 
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: harsh98trivedi
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

    # FACEBOOK
  - Name: Facebook
    URL: https://www.facebook.com
    Username: devsresnetwork 
    Color: '#3b5998'
    Icon-Class: fab fa-facebook

    # BUY ME A COFFEE
  - Name: BuyMeACoffee
    URL: 'https://buymeacoffee.com'
    Username: marcelo_devsres 
    Icon-Class: fas fa-mug-hot
    Color: '#FFDD00'
    Text_Color: '#000000'

    # TELEGRAM
  - Name: Telegram
    URL: http://t.me
    Username: devsres
    Color: '#0088cc'
    Icon-Class: fab fa-telegram-plane

    # EMAIL
  - Name: Email
    URL: 'mailto:contact@devsres.com'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'


    # CLUBHOUSE
  - Name: Clubhouse
    URL: 
    Username: '@harsh98trivedi'
    Color: '#f1c40f'
    Icon-Class: fas fa-hand-paper -mt-0.5
    
    # VIMEO
  - Name: Vimeo
    URL: 
    Username: harshtrivedi
    Icon-Class: fab fa-vimeo-v
    Color: '#1ab7ea'
    Text_Color: '#ffffff'

    # MESSENGER
  - Name: Messenger
    URL: 
    Username: theharshtrivedi
    Color: '#006AFF'
    Icon-Class: fab fa-facebook-messenger

    # REDDIT
  - Name: Reddit
    URL: 
    Username: harshtrivedi
    Color: '#FF4500'
    Icon-Class: fab fa-reddit-alien

  #   # WHATSAPP
  # - Name: WhatsApp
  #   URL: https://wa.me
  #   Username: '+1123456789'
  #   Color: '#25d366'
  #   Icon-Class: fab fa-whatsapp


    # SNAPCHAT
  - Name: Snapchat
    URL: 
    Username: 'harsh98trivedi'
    Color: '#FFFC00'
    Text_Color: '#000000'
    Icon-Class: fab fa-snapchat-ghost

  #   # DISCORD
  # - Name: Discord
  #   URL: 'https://discord.gg'
  #   Username: 
  #   Icon-Class: fab fa-discord
  #   Color: '#5865F2'
  #   Text_Color: '#ffffff'

    # PINTEREST
  - Name: Pinterest
    URL: 
    Username: 'harsh98trivedi'
    Color: '#E60023'
    Icon-Class: fab fa-pinterest

    # BEHANCE
  - Name: Behance
    URL: 
    Username: harsh98trivedi
    Color: '#1769ff'
    Icon-Class: fab fa-behance

  #   # DRIBBBLE
  # - Name: Dribbble
  #   URL: https://dribbble.com
  #   Username: 
  #   Color: '#ea4c89'
  #   Icon-Class: fab fa-dribbble

    # DEVIANTART
  - Name: DeviantArt
    URL: 
    Username: harshtrivedi
    Icon-Class: fab fa-deviantart
    Color: '#05CC46'
    Text_Color: '#ffffff'

    # FIGMA
  - Name: Figma
    URL: 
    Username: '@harshtrivedi'
    Icon-Class: fab fa-figma
    Color: '#ff2865'
    Text_Color: '#ffffff'

    # SPOTIFY
  - Name: Spotify
    URL: 
    Username: 314ihryk3edvtusti6il3oy3x5da
    Color: '#1DB954'
    Icon-Class: fab fa-spotify

    # SOUNDCLOUD
  - Name: SoundCloud
    URL: 
    Username: harsh98trivedi
    Color: '#FE5000'
    Icon-Class: fab fa-soundcloud

  #    # TIKTOK
  # - Name: TikTok
  #   URL: https://www.tiktok.com
  #   Username: 
  #   Color: '#FE2C55'
  #   Icon-Class: fab fa-tiktok

    # MEDIUM
  - Name: Medium
    URL: 
    Username: '@harsh98trivedi'
    Icon-Class: fab fa-medium-m
    Color: '#00ab6c'
    Text_Color: '#ffffff'

  #   # TUMBLR
  # - Name: Tumblr
  #   URL: https://www.tumblr.com
  #   Username: 
  #   Color: '#35465c'
  #   Icon-Class: fab fa-tumblr


    # CUSTOM LINK
  - Name: Blog
    URL: 
    Icon-Class: fas fa-link
    Color: '#ffb142'
    Text_Color: '#ffffff'

  - Name: Links
    URL: 
    Icon-Class: fas fa-link
    Color: '#d94869'
    Text_Color: '#ffffff'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: ''

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
baseurl: /links

# Default Markdown Engine
markdown: kramdown
